# Generated by Django 5.1.7 on 2025-03-11 04:00

from django.db import migrations
from django.contrib.auth import get_user_model


def assign_projects_to_user(apps, schema_editor):
    # Get the Project model
    Project = apps.get_model('todo_lists', 'Project')
    User = get_user_model()
    
    # Skip if no projects or if they already have users assigned
    if Project.objects.filter(user__isnull=True).count() == 0:
        return
    
    # Get the first user or create a default admin user
    try:
        default_user = User.objects.first()
        if not default_user:
            default_user = User.objects.create_superuser(
                username='admin',
                email='admin@example.com',
                password='admin123'  # This should be changed after first login
            )
            print("Created a default admin user. Please change the password after first login.")
    except Exception as e:
        print(f"Error creating or getting default user: {e}")
        return
    
    # Assign all projects without a user to the default user
    Project.objects.filter(user__isnull=True).update(user=default_user)
    print(f"Assigned all existing projects to user: {default_user.username}")


def reverse_migration(apps, schema_editor):
    # No need to reverse since we're just assigning data
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0003_project_user'),
    ]

    operations = [
        migrations.RunPython(assign_projects_to_user, reverse_migration),
    ]
